<?php




$paises =array(
array('id_pais'=>'0', 'nombre_pais'=>'Afganistán'),
array('id_pais'=>'1', 'nombre_pais'=>'Albania'),
array('id_pais'=>'2', 'nombre_pais'=>'Alemania'),
array('id_pais'=>'3', 'nombre_pais'=>'Andorra'),
array('id_pais'=>'4', 'nombre_pais'=>'Angola'),
array('id_pais'=>'5', 'nombre_pais'=>'Antigua y Barbuda'),
array('id_pais'=>'6', 'nombre_pais'=>'Arabia Saudita'),
array('id_pais'=>'7', 'nombre_pais'=>'Argelia'),
array('id_pais'=>'8', 'nombre_pais'=>'Argentina'),
array('id_pais'=>'9', 'nombre_pais'=>'Armenia'),
array('id_pais'=>'10', 'nombre_pais'=>'Australia'),
array('id_pais'=>'11', 'nombre_pais'=>'Austria'),
array('id_pais'=>'12', 'nombre_pais'=>'Azerbaiyán'),
array('id_pais'=>'13', 'nombre_pais'=>'Bahamas'),
array('id_pais'=>'14', 'nombre_pais'=>'Bangladés'),
array('id_pais'=>'15', 'nombre_pais'=>'Barbados'),
array('id_pais'=>'16', 'nombre_pais'=>'Baréin'),
array('id_pais'=>'17', 'nombre_pais'=>'Bélgica'),
array('id_pais'=>'18', 'nombre_pais'=>'Belice'),
array('id_pais'=>'19', 'nombre_pais'=>'Benín'),
array('id_pais'=>'20', 'nombre_pais'=>'Bielorrusia'),
array('id_pais'=>'21', 'nombre_pais'=>'Birmania'),
array('id_pais'=>'22', 'nombre_pais'=>'Bolivia'),
array('id_pais'=>'23', 'nombre_pais'=>'Bosnia y Herzegovina'),
array('id_pais'=>'24', 'nombre_pais'=>'Botsuana'),
array('id_pais'=>'25', 'nombre_pais'=>'Brasil'),
array('id_pais'=>'26', 'nombre_pais'=>'Brunéi'),
array('id_pais'=>'27', 'nombre_pais'=>'Bulgaria'),
array('id_pais'=>'28', 'nombre_pais'=>'Burkina Faso'),
array('id_pais'=>'29', 'nombre_pais'=>'Burundi'),
array('id_pais'=>'30', 'nombre_pais'=>'Bután'),
array('id_pais'=>'31', 'nombre_pais'=>'Cabo Verde'),
array('id_pais'=>'32', 'nombre_pais'=>'Camboya'),
array('id_pais'=>'33', 'nombre_pais'=>'Camerún'),
array('id_pais'=>'34', 'nombre_pais'=>'Canadá'),
array('id_pais'=>'35', 'nombre_pais'=>'Catar'),
array('id_pais'=>'36', 'nombre_pais'=>'Chad'),
array('id_pais'=>'37', 'nombre_pais'=>'Chile'),
array('id_pais'=>'38', 'nombre_pais'=>'China'),
array('id_pais'=>'39', 'nombre_pais'=>'Chipre'),
array('id_pais'=>'40', 'nombre_pais'=>'Ciudad del Vaticano'),
array('id_pais'=>'41', 'nombre_pais'=>'Colombia'),
array('id_pais'=>'42', 'nombre_pais'=>'Comoras'),
array('id_pais'=>'43', 'nombre_pais'=>'Corea del Norte'),
array('id_pais'=>'44', 'nombre_pais'=>'Corea del Sur'),
array('id_pais'=>'45', 'nombre_pais'=>'Costa de Marfil'),
array('id_pais'=>'46', 'nombre_pais'=>'Costa Rica'),
array('id_pais'=>'47', 'nombre_pais'=>'Croacia'),
array('id_pais'=>'48', 'nombre_pais'=>'Cuba'),
array('id_pais'=>'49', 'nombre_pais'=>'Dinamarca'),
array('id_pais'=>'50', 'nombre_pais'=>'Dominica'),
array('id_pais'=>'51', 'nombre_pais'=>'Ecuador'),
array('id_pais'=>'52', 'nombre_pais'=>'Egipto'),
array('id_pais'=>'53', 'nombre_pais'=>'El Salvador'),
array('id_pais'=>'54', 'nombre_pais'=>'Emiratos Árabes Unidos'),
array('id_pais'=>'55', 'nombre_pais'=>'Eritrea'),
array('id_pais'=>'56', 'nombre_pais'=>'Eslovaquia'),
array('id_pais'=>'57', 'nombre_pais'=>'Eslovenia'),
array('id_pais'=>'58', 'nombre_pais'=>'España'),
array('id_pais'=>'59', 'nombre_pais'=>'Estados Unidos'),
array('id_pais'=>'60', 'nombre_pais'=>'Estonia'),
array('id_pais'=>'61', 'nombre_pais'=>'Etiopía'),
array('id_pais'=>'62', 'nombre_pais'=>'Filipinas'),
array('id_pais'=>'63', 'nombre_pais'=>'Finlandia'),
array('id_pais'=>'64', 'nombre_pais'=>'Fiyi'),
array('id_pais'=>'65', 'nombre_pais'=>'Francia'),
array('id_pais'=>'66', 'nombre_pais'=>'Gabón'),
array('id_pais'=>'67', 'nombre_pais'=>'Gambia'),
array('id_pais'=>'68', 'nombre_pais'=>'Georgia'),
array('id_pais'=>'69', 'nombre_pais'=>'Ghana'),
array('id_pais'=>'70', 'nombre_pais'=>'Granada'),
array('id_pais'=>'71', 'nombre_pais'=>'Grecia'),
array('id_pais'=>'72', 'nombre_pais'=>'Guatemala'),
array('id_pais'=>'73', 'nombre_pais'=>'Guyana'),
array('id_pais'=>'74', 'nombre_pais'=>'Guinea'),
array('id_pais'=>'75', 'nombre_pais'=>'Guinea ecuatorial'),
array('id_pais'=>'76', 'nombre_pais'=>'Guinea-Bisáu'),
array('id_pais'=>'77', 'nombre_pais'=>'Haití'),
array('id_pais'=>'78', 'nombre_pais'=>'Honduras'),
array('id_pais'=>'79', 'nombre_pais'=>'Hungría'),
array('id_pais'=>'80', 'nombre_pais'=>'India'),
array('id_pais'=>'81', 'nombre_pais'=>'Indonesia'),
array('id_pais'=>'82', 'nombre_pais'=>'Irak'),
array('id_pais'=>'83', 'nombre_pais'=>'Irán'),
array('id_pais'=>'84', 'nombre_pais'=>'Irlanda'),
array('id_pais'=>'85', 'nombre_pais'=>'Islandia'),
array('id_pais'=>'86', 'nombre_pais'=>'Islas Marshall'),
array('id_pais'=>'87', 'nombre_pais'=>'Islas Salomón'),
array('id_pais'=>'88', 'nombre_pais'=>'Israel'),
array('id_pais'=>'89', 'nombre_pais'=>'Italia'),
array('id_pais'=>'90', 'nombre_pais'=>'Jamaica'),
array('id_pais'=>'91', 'nombre_pais'=>'Japón'),
array('id_pais'=>'92', 'nombre_pais'=>'Jordania'),
array('id_pais'=>'93', 'nombre_pais'=>'Kazajistán'),
array('id_pais'=>'94', 'nombre_pais'=>'Kenia'),
array('id_pais'=>'95', 'nombre_pais'=>'Kirguistán'),
array('id_pais'=>'96', 'nombre_pais'=>'Kiribati'),
array('id_pais'=>'97', 'nombre_pais'=>'Kuwait'),
array('id_pais'=>'98', 'nombre_pais'=>'Laos'),
array('id_pais'=>'99', 'nombre_pais'=>'Lesoto'),
array('id_pais'=>'100', 'nombre_pais'=>'Letonia'),
array('id_pais'=>'101', 'nombre_pais'=>'Líbano'),
array('id_pais'=>'102', 'nombre_pais'=>'Liberia'),
array('id_pais'=>'103', 'nombre_pais'=>'Libia'),
array('id_pais'=>'104', 'nombre_pais'=>'Liechtenstein'),
array('id_pais'=>'105', 'nombre_pais'=>'Lituania'),
array('id_pais'=>'106', 'nombre_pais'=>'Luxemburgo'),
array('id_pais'=>'107', 'nombre_pais'=>'Madagascar'),
array('id_pais'=>'108', 'nombre_pais'=>'Malasia'),
array('id_pais'=>'109', 'nombre_pais'=>'Malaui'),
array('id_pais'=>'110', 'nombre_pais'=>'Maldivas'),
array('id_pais'=>'111', 'nombre_pais'=>'Malí'),
array('id_pais'=>'112', 'nombre_pais'=>'Malta'),
array('id_pais'=>'113', 'nombre_pais'=>'Marruecos'),
array('id_pais'=>'114', 'nombre_pais'=>'Mauricio'),
array('id_pais'=>'115', 'nombre_pais'=>'Mauritania'),
array('id_pais'=>'116', 'nombre_pais'=>'México'),
array('id_pais'=>'117', 'nombre_pais'=>'Micronesia'),
array('id_pais'=>'118', 'nombre_pais'=>'Moldavia'),
array('id_pais'=>'119', 'nombre_pais'=>'Mónaco'),
array('id_pais'=>'120', 'nombre_pais'=>'Mongolia'),
array('id_pais'=>'121', 'nombre_pais'=>'Montenegro'),
array('id_pais'=>'122', 'nombre_pais'=>'Mozambique'),
array('id_pais'=>'123', 'nombre_pais'=>'Namibia'),
array('id_pais'=>'124', 'nombre_pais'=>'Nauru'),
array('id_pais'=>'125', 'nombre_pais'=>'Nepal'),
array('id_pais'=>'126', 'nombre_pais'=>'Nicaragua'),
array('id_pais'=>'127', 'nombre_pais'=>'Níger'),
array('id_pais'=>'128', 'nombre_pais'=>'Nigeria'),
array('id_pais'=>'129', 'nombre_pais'=>'Noruega'),
array('id_pais'=>'130', 'nombre_pais'=>'Nueva Zelanda'),
array('id_pais'=>'131', 'nombre_pais'=>'Omán'),
array('id_pais'=>'132', 'nombre_pais'=>'Países Bajos'),
array('id_pais'=>'133', 'nombre_pais'=>'Pakistán'),
array('id_pais'=>'134', 'nombre_pais'=>'Palaos'),
array('id_pais'=>'135', 'nombre_pais'=>'Palestina'),
array('id_pais'=>'136', 'nombre_pais'=>'Panamá'),
array('id_pais'=>'137', 'nombre_pais'=>'Papúa Nueva Guinea'),
array('id_pais'=>'138', 'nombre_pais'=>'Paraguay'),
array('id_pais'=>'139', 'nombre_pais'=>'Perú'),
array('id_pais'=>'140', 'nombre_pais'=>'Polonia'),
array('id_pais'=>'141', 'nombre_pais'=>'Portugal'),
array('id_pais'=>'142', 'nombre_pais'=>'Reino Unido'),
array('id_pais'=>'143', 'nombre_pais'=>'República Centroafricana'),
array('id_pais'=>'144', 'nombre_pais'=>'República Checa'),
array('id_pais'=>'145', 'nombre_pais'=>'República de Macedonia'),
array('id_pais'=>'146', 'nombre_pais'=>'República del Congo'),
array('id_pais'=>'147', 'nombre_pais'=>'República Democrática del Congo'),
array('id_pais'=>'148', 'nombre_pais'=>'República Dominicana'),
array('id_pais'=>'149', 'nombre_pais'=>'República Sudafricana'),
array('id_pais'=>'150', 'nombre_pais'=>'Ruanda'),
array('id_pais'=>'151', 'nombre_pais'=>'Rumanía'),
array('id_pais'=>'152', 'nombre_pais'=>'Rusia'),
array('id_pais'=>'153', 'nombre_pais'=>'Samoa'),
array('id_pais'=>'154', 'nombre_pais'=>'San Cristóbal y Nieves'),
array('id_pais'=>'155', 'nombre_pais'=>'San Marino'),
array('id_pais'=>'156', 'nombre_pais'=>'San Vicente y las Granadinas'),
array('id_pais'=>'157', 'nombre_pais'=>'Santa Lucía'),
array('id_pais'=>'158', 'nombre_pais'=>'Santo Tomé y Príncipe'),
array('id_pais'=>'159', 'nombre_pais'=>'Senegal'),
array('id_pais'=>'160', 'nombre_pais'=>'Serbia'),
array('id_pais'=>'161', 'nombre_pais'=>'Seychelles'),
array('id_pais'=>'162', 'nombre_pais'=>'Sierra Leona'),
array('id_pais'=>'163', 'nombre_pais'=>'Singapur'),
array('id_pais'=>'164', 'nombre_pais'=>'Siria'),
array('id_pais'=>'165', 'nombre_pais'=>'Somalia'),
array('id_pais'=>'166', 'nombre_pais'=>'Sri Lanka'),
array('id_pais'=>'167', 'nombre_pais'=>'Suazilandia'),
array('id_pais'=>'168', 'nombre_pais'=>'Sudán'),
array('id_pais'=>'169', 'nombre_pais'=>'Sudán del Sur'),
array('id_pais'=>'170', 'nombre_pais'=>'Suecia'),
array('id_pais'=>'171', 'nombre_pais'=>'Suiza'),
array('id_pais'=>'172', 'nombre_pais'=>'Surinam'),
array('id_pais'=>'173', 'nombre_pais'=>'Tailandia'),
array('id_pais'=>'174', 'nombre_pais'=>'Tanzania'),
array('id_pais'=>'175', 'nombre_pais'=>'Tayikistán'),
array('id_pais'=>'176', 'nombre_pais'=>'Timor Oriental'),
array('id_pais'=>'177', 'nombre_pais'=>'Togo'),
array('id_pais'=>'178', 'nombre_pais'=>'Tonga'),
array('id_pais'=>'179', 'nombre_pais'=>'Trinidad y Tobago'),
array('id_pais'=>'180', 'nombre_pais'=>'Túnez'),
array('id_pais'=>'181', 'nombre_pais'=>'Turkmenistán'),
array('id_pais'=>'182', 'nombre_pais'=>'Turquía'),
array('id_pais'=>'183', 'nombre_pais'=>'Tuvalu'),
array('id_pais'=>'184', 'nombre_pais'=>'Ucrania'),
array('id_pais'=>'185', 'nombre_pais'=>'Uganda'),
array('id_pais'=>'186', 'nombre_pais'=>'Uruguay'),
array('id_pais'=>'187', 'nombre_pais'=>'Uzbekistán'),
array('id_pais'=>'188', 'nombre_pais'=>'Vanuatu'),
array('id_pais'=>'189', 'nombre_pais'=>'Venezuela'),
array('id_pais'=>'190', 'nombre_pais'=>'Vietnam'),
array('id_pais'=>'191', 'nombre_pais'=>'Yemen'),
array('id_pais'=>'192', 'nombre_pais'=>'Yibuti'),
array('id_pais'=>'193', 'nombre_pais'=>'Zambia'),
array('id_pais'=>'194', 'nombre_pais'=>'Zimbabue'),
); 
 ?>